### ISSUE TITLE
无法调用

### ISSUE THREAD

**Issue by zeng8280** [yzhao062/combo#1]

**Comment by zeng8280** [comment]
你好，mac电脑按照如图方法下载了 这个包 但是无法调用里面的stacking， 显示的是No module named 'combo.models.stacking' 在models文件夹里面也未发现stacking命名的文件，不知道是哪里出问题了

**Comment by zeng8280** [comment]
找到原因了 在exampled的stacking里面看见了 stacking包在classifier_stacking 名下， 所以应该是from combo.models.classifier_stacking import Stacking  read_me文档里的这个细节也请改动下

**Comment by yzhao062** [comment]
感谢反馈。文档在文件改名后忘了及时更新，现在应该同步了~
