### ISSUE TITLE
LightGBM 的支持

### ISSUE THREAD

**Issue by Foristkirito** [yzhao062/combo#4]
AttributeError: 'LGBMRanker' object has no attribute 'fitted_'

**Comment by yzhao062** [comment]
Thanks. I have not testst on LightGBM and catboost but only sckit-learn and xgboost. 
This should be easy to address and I will update in the next version. Will update you here.

**Comment by yzhao062** [comment]
Hi there,

Only classification is supported for combining models from scikit-learn, xgboost, and lightGBM. See this example for more information: https://github.com/yzhao062/combo/blob/master/examples/classifier_multiple_libs.py

I guess LGBRanker would not work as it is a valid classifier. Hope this information helps.
